#!/bin/bash
program="kvash"
version="0.9.0"

errorBanner="$(cat <<-EOF
error during command or command not found.
type ${program} help for help."
EOF
)"

helpMessage="$(cat <<-EOF
${program} ${version}

HELP
----

SCOPE
-----

- each key is a file, so do not use this tool as a massive storage (you do not want millions of ionodes isn't it ?)
- the goal is not to replace or mimic a 'true' key value storage
- the goal is to store embedded state when a 'true' key value storage seems overkill
- this tool helps to have list and dict types for your states in bash

TYPES
-----

- string: set/get
- list: list commands
- dict: dict commands, dicts can be exported as env variables

COMMANDS
--------

location of your store (main directory path) should be set in KVASH_STORE var env
example: export KVASH_STORE="\${HOME}/kvstore/store1"

there is no explicit ${program} "clear" command, please use rm "\${KVASH_STORE}/*" to delete all the store (all the keys) 

help:
${program} help

list keys:
${program} ls [search]

touch a key
${program} touch key
will not erase content if exists

set value:
${program} set key value

append:
${program} append key value
please do not add content to a list/dict key until you know what you do

append with crlf after value:
${program} appendr key value
please do not add content to a list/dict key until you know what you do

get key file full path:
${program} path key

remove key:
${program} del key

list add item:
${program} list add key item

list del item:
${program} list del key
no duplicates expected in your use case ? before list add you can always call list del

list foreach key callback:
export -f callback
${program} list foreach key callback
item is passed as \$1 in callback

dict set prop:
${program} dict set key prop value comment

dict get prop:
${program} dict get key prop
export prop=\$(${program} dict get key prop)

dict get props as args:
${program} dict props key
export \$(${program} dict props key)

dict del prop:
${program} dict del key prop

EOF
)"

#
# TOOLS
#

# check arg
# checkArg name var
checkArg () {
    if [ -z "$2" ]; then
      echo "argument missing: $1"
      exit 1
   fi
}

#
# HANDLERS
#

handler_help () {
    echo "${helpMessage}"
    exit
}

#
# ls [search]
#
handler_ls () {
    local search="$1"

    [ -n "${search}" ] && ls -1 "${store}/${key}" | (grep "${search}" || echo "") || ls -1 "${store}/${key}"
}

#
# touch key
#
handler_touch () {
    local key="$1"

    checkArg key "${key}"

    touch "${store}/${key}"
}


#
# has key
#
handler_has () {
    local key="$1"

    checkArg key "${key}"

    [ -f "${store}/${key}" ] && echo "true" || echo "false"
}

#
# set key value
#
handler_set () {
    local key="$1"
    local value="${*:2}"

    checkArg key "${key}"
    checkArg value "${value}"

    echo -n "${value}" > "${store}/${key}"
}

#
# append key value
#
handler_append () {
    local key="$1"
    local value="${*:2}"

    checkArg key "${key}"
    checkArg value "${value}"

    echo  -n "${value}" >> "${store}/${key}"
}

#
# appendr key value
# (line after value)
#
handler_appendr () {
    local key="$1"
    local value="${*:2}"

    checkArg key "${key}"
    checkArg value "${value}"

    echo -n "${value}" >> "${store}/${key}"
    echo "" >> "${store}/${key}"
}

#
# get key
#
handler_get () {
    local key="$1"

    checkArg key "${key}"

    cat "${store}/${key}"
}


#
# path key
#
handler_path () {
    local key="$1"

    checkArg key "${key}"

    echo "${store}/${key}"
}


#
# del key
#
handler_del () {
    local key="$1"

    checkArg key "${key}"

    rm "${store}/${key}" 2> /dev/null
}


#
# list key ...args
#
handler_list () {
    local listCommand="$1"

    checkArg command "${listCommand}"

    declare -F "handler_list_${listCommand}" &> /dev/null && "handler_list_${listCommand}" ${@:2} || echo "${errorBanner}"
}

# list add key item
handler_list_add () {
    local key="$1"
    local item="$2"

    checkArg key "${key}"
    checkArg item "${item}"

    handler_appendr "${key}" "${item}"
}

# list del key item
handler_list_del () {
    local key="$1"
    local item="$2"

    checkArg key "${key}"
    checkArg item "${item}"

    # IMPORTANT: match exact word ^*$ to prevent from removing entries that are not exact (like ending by prop)
    # IMPORTANT: target file can not be the source file, a pivot file is used
    cat "${store}/${key}" | (grep -v "^${item}\$" || echo "") > "${store}/${key}.tmp"
    sed '/^$/d' "${store}/${key}.tmp" > "${store}/${key}" # remove empty lines
    rm "${store}/${key}.tmp"
}

# list foreach key callback
# item will be $1 in callback
handler_list_foreach () {
    local key="$1"
    local callback="$2"

    checkArg key "${key}"
    checkArg callback "${callback}"

    # remove empty lines
    sed '/^$/d' "${store}/${key}" > "${store}/${key}.tmp"

    while read item; do "${callback}" "${item}"; done < "${store}/${key}.tmp"

    rm "${store}/${key}.tmp"
}


#
# dict key ...args
#
handler_dict () {
    local dictCommand="$1"
    local dictCommandFunctionName="$1"

    checkArg command "${dictCommand}"

    declare -F "handler_dict_${dictCommandFunctionName}" &> /dev/null && "handler_dict_${dictCommandFunctionName}" ${@:2} || echo "${errorBanner}"
}

# dict set key prop value
handler_dict_set () {
    local key="$1"
    local prop="$2"
    local value="${*:3}"

    checkArg key "${key}"
    checkArg prop "${prop}"
    checkArg value "${value}"

    handler_touch "${key}"
    handler_dict_del "${key}" "${prop}"
    handler_list_add "${key}" "${prop}=${value}"
}

# dict get key prop
handler_dict_get () {
    local key="$1"
    local prop="$2"

    checkArg key "${key}"
    checkArg prop "${prop}"

    export $(handler_get "${key}" | (grep "^${prop}=" || echo ""))
    echo "${!prop}"
}

# dict get key props
handler_dict_props () {
    local key="$1"

    checkArg key "${key}"

    handler_get "${key}" | xargs
}

# dict foreach key callback
# prop will be $1 in callback, its value $2
handler_dict_foreach () {
    local key="$1"
    local callback="$2"

    checkArg key "${key}"
    checkArg callback "${callback}"

    # remove empty lines
    sed '/^$/d' "${store}/${key}" > "${store}/${key}.tmp"

    while read item; do
        IFS='=' read -r -a array <<< "$item"
        "${callback}" "${array[0]}" "${array[1]}"
    done < "${store}/${key}.tmp"

    rm "${store}/${key}.tmp"
}

# dict del key prop
handler_dict_del () {
    local key="$1"
    local prop="$2"

    checkArg key "${key}"
    checkArg prop "${prop}"

    # IMPORTANT: match start word ^ to prevent from removing entries that are not exact (like ending by prop)
    # IMPORTANT: target file can not be the source file, a pivot file is used
    cat "${store}/${key}" | (grep -v "^${prop}=" || echo "") > "${store}/.${key}"
    sed '/^$/d' "${store}/.${key}" > "${store}/${key}" # remove empty lines
}


#
# BODY
#
main () {
    [ -z ${command} ] && command="help"
    store=${KVASH_STORE}

    if [ "${command}" != "help" ] && [ -z "${store}" ]; then
        echo "aborted. target store absolute path should be pointed with KVASH_STORE environment variable"
        exit
    fi

    [ "${command}" != "help" ] && mkdir -p "${store}"

    declare -F "handler_${command}" &> /dev/null && "handler_${command}" $@ || echo "${errorBanner}"
}

command="$1"
commandFunctionName="$1"
store=${KVASH_STORE}
cwd=$(pwd)

main ${@:2}
